# Generated by Django 2.1.7 on 2019-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='img_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='事件图片链接'),
        ),
        migrations.AddField(
            model_name='detail',
            name='video_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='事件视频'),
        ),
    ]
