# Generated by Django 2.1.7 on 2019-03-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timemessage', '0002_auto_20190320_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='img_url',
            field=models.TextField(blank=True, null=True, verbose_name='事件图片链接'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='事件视频'),
        ),
    ]
