# Generated by Django 2.1.7 on 2019-03-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timemessage', '0003_auto_20190320_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='video_url',
        ),
    ]
