# Generated by Django 2.1.7 on 2019-03-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timemessage', '0004_auto_20190320_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='事件图片链接')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timemessage.Detail')),
            ],
            options={
                'verbose_name': '事件图片资源',
                'verbose_name_plural': '事件图片资源',
            },
        ),
        migrations.CreateModel(
            name='SourceVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='事件视频链接')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timemessage.Detail')),
            ],
            options={
                'verbose_name': '事件图片资源',
                'verbose_name_plural': '事件图片资源',
            },
        ),
    ]
