# Generated by Django 2.1.7 on 2019-03-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timemessage', '0005_sourceimg_sourcevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcevideo',
            options={'verbose_name': '事件视频资源', 'verbose_name_plural': '事件视频资源'},
        ),
    ]
